### PR TITLE
Bug/issue fixes

### PR DESCRIPTION
**Pull request by eserpin**
@kennyctran 
Fixed bug in overview where on product change the image index of the current gallery photo would stay the same.

Also changed all the post requests and routes to get routes to make them RESTful.

I wanna talk to colin a little more about the middleware he said we could implement in the code review before I try anything stupid. Looks like he's offline for today so I'll ask when he has time.

### CODE REVIEW

**Review by kennyctran — CHANGES_REQUESTED** [review]
While you're here, could you also edit the tests in endpoints.test.JS to match the new routes? Should be pretty straight forward but give it a go, uncomment them, then run a jest test to make sure they're passing.

**Comment by eserpin** [comment]
@kennyctran 
I changed the tests and I believe they're working. I've left a pic of the yarn test results.

There's some snapshot fails for some of your components and I don't remember how you told me those are fixed, but maybe you can handle that on your end? If not just hit me on slack telling me how and I'll fix it up.

> 

> 
Screen Shot 2021-04-30 at 7 46 17 PM

**Comment by kennyctran** [comment]
You'll want to remove the x from describe in the Atelier API non-stubbed. In the test when running you should see the requests logged from the server. You might have to do a quick Google for super test and superagemt because i don't know if .query is a thing. 

And you can run yarn jest --updateSnapshots

**Comment by eserpin** [comment]
Yeah I had googled it already. They all work, but since we have a console.error(err) server-side, theres a lot of red in the console when it tests and its kinda ugly lol.

I updated the snapshots and everything looks good.

Screen Shot 2021-04-30 at 8 04 11 PM

**Comment by kennyctran** [comment]
Great! Yeah I don't run the intentional error requests because of all the error logs. Looks good! Thanks!

**Review by kennyctran — APPROVED** [review]
All good to merge.

**Pull request merged**
